name: Tebex
version: '${version}'
main: io.tebex.plugin.TebexBukkitPlugin
api-version: 1.13
softdepend:
  - BuycraftX
  - HuskSync
commands:
  tebex:
    description: The main command
    aliases:
      - buycraft