name: Tebex
version: '${version}'
main: io.tebex.plugin.TebexPlugin
api-version: 1.13
softdepend:
  - BuycraftX
  - floodgate
commands:
  analytics:
    description: The main command
    permission: analytics.admin
    aliases:
      - analyse
      - tebexanalytics
  tebex:
    description: The main command
    aliases:
      - buycraft
permissions:
  analytics.admin:
    description: Allows debug command
    default: op
  analytics.debug:
    description: Allows debug command
    default: op
  analytics.reload:
    description: Allows reload command
    default: op
  analytics.setup:
    description: Allows setup command
    default: op
  analytics.stats:
    description: Allows stats command
    default: op
  analytics.track:
    description: Allows track command
    default: op
  analytics.*:
    description: Wildcard permission
    default: op
    children:
      analytics.admin: true
      analytics.debug: true
      analytics.reload: true
      analytics.setup: true
      analytics.stats: true
      analytics.track: true